
name: Daily Run Script

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点UTC运行
  workflow_dispatch:      # 也允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests lxml ics

    - name: Run Python script
      run: python run3.py

    - name: Commit generated movies.ics
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add movies.ics
        git commit -m "Update movies.ics [skip ci]" || echo "No changes to commit"
        git push
